version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
      - "5432"

  web:
    build: .
    # Используем переменные для имени образа из GitHub Actions
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build: ./nginx
    # Используем переменные для имени образа из GitHub Actions
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443" # Оставьте для будущего HTTPS
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: