# materials/migrations/0004_course_price.py
# Generated by Django X.Y.Z on YYYY-MM-DD HH:MM
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.00, help_text='Цена курса в рублях или другой валюте', max_digits=10, verbose_name='Цена'),
        ),
    ]