# Generated by Django 4.2.25 on 2025-10-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Цена курса в рублях/валюте', max_digits=10, verbose_name='Цена'),
        ),
    ]
