# Generated by Django 4.2.25 on 2025-10-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10, verbose_name='Цена курса'),
        ),
    ]
