# Generated by Django 4.2.25 on 2025-10-30 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее обновление'),
        ),
    ]
