# Generated by Django 5.2.7 on 2025-10-14 (manual data migration)

from django.db import migrations


def create_moderators_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='moderators')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.RunPython(create_moderators_group),
    ]